#pragma once


#include <unordered_map>
#include <string>


std::string get_extension(std::string mime) {
    const static std::unordered_map<std::string, std::string> map = {
        // Text
        { "text/plain", ".txt" },
        { "text/html", ".html" },
        { "text/css", ".css" },
        { "text/javascript", ".js" },
        { "text/markdown", ".md" },
        { "text/csv", ".csv" },
        { "text/xml", ".xml" },
        { "text/x-c", ".c" },
        { "text/x-c++", ".cpp" },
        { "text/x-java", ".java" },
        { "text/x-python", ".py" },
        { "text/x-perl", ".pl" },
        { "text/x-php", ".php" },
        { "text/x-ruby", ".rb" },
        { "text/x-sh", ".sh" },
        { "text/x-go", ".go" },
        { "text/x-rust", ".rs" },
        { "text/x-swift", ".swift" },
        { "text/x-tex", ".tex" },
        { "text/x-yaml", ".yml" },
        { "text/x-properties", ".properties" },
        { "text/calendar", ".ics" },
        { "text/vcard", ".vcf" },
        { "text/x-log", ".log" },

        // Images
        { "image/jpeg", ".jpg" },
        { "image/png", ".png" },
        { "image/gif", ".gif" },
        { "image/webp", ".webp" },
        { "image/svg+xml", ".svg" },
        { "image/bmp", ".bmp" },
        { "image/tiff", ".tiff" },
        { "image/x-icon", ".ico" },
        { "image/vnd.microsoft.icon", ".ico" },
        { "image/heic", ".heic" },
        { "image/heif", ".heif" },
        { "image/avif", ".avif" },
        { "image/apng", ".apng" },

        // Audio
        { "audio/mpeg", ".mp3" },
        { "audio/ogg", ".ogg" },
        { "audio/wav", ".wav" },
        { "audio/webm", ".weba" },
        { "audio/aac", ".aac" },
        { "audio/midi", ".midi" },
        { "audio/x-midi", ".mid" },
        { "audio/flac", ".flac" },
        { "audio/opus", ".opus" },
        { "audio/vorbis", ".vorbis" },
        { "audio/3gpp", ".3gpp" },
        { "audio/3gpp2", ".3g2" },
        { "audio/mp4", ".m4a" },
        { "audio/x-ms-wma", ".wma" },

        // Video
        { "video/mp4", ".mp4" },
        { "video/mpeg", ".mpeg" },
        { "video/webm", ".webm" },
        { "video/ogg", ".ogv" },
        { "video/x-msvideo", ".avi" },
        { "video/3gpp", ".3gp" },
        { "video/3gpp2", ".3g2" },
        { "video/mp2t", ".ts" },
        { "video/x-matroska", ".mkv" },
        { "video/x-ms-wmv", ".wmv" },
        { "video/x-flv", ".flv" },
        { "video/quicktime", ".mov" },
        { "video/x-ms-asf", ".asf" },

        // Documents
        { "application/pdf", ".pdf" },
        { "application/msword", ".doc" },
        { "application/vnd.openxmlformats-officedocument.wordprocessingml.document", ".docx" },
        { "application/vnd.ms-excel", ".xls" },
        { "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ".xlsx" },
        { "application/vnd.ms-powerpoint", ".ppt" },
        { "application/vnd.openxmlformats-officedocument.presentationml.presentation", ".pptx" },
        { "application/rtf", ".rtf" },
        { "application/vnd.oasis.opendocument.text", ".odt" },
        { "application/vnd.oasis.opendocument.spreadsheet", ".ods" },
        { "application/vnd.oasis.opendocument.presentation", ".odp" },
        { "application/epub+zip", ".epub" },
        { "application/x-mobipocket-ebook", ".mobi" },
        { "application/vnd.amazon.ebook", ".azw" },
        { "application/vnd.openxmlformats-officedocument.wordprocessingml.template", ".dotx" },
        { "application/vnd.ms-excel.template.macroEnabled.12", ".xltx" },
        { "application/vnd.ms-powerpoint.template.macroEnabled.12", ".potx" },

        // Archives
        { "application/zip", ".zip" },
        { "application/x-zip-compressed", ".zip" },
        { "application/x-7z-compressed", ".7z" },
        { "application/x-rar-compressed", ".rar" },
        { "application/gzip", ".gz" },
        { "application/x-tar", ".tar" },
        { "application/x-bzip", ".bz" },
        { "application/x-bzip2", ".bz2" },
        { "application/x-xz", ".xz" },
        { "application/x-zstd", ".zst" },
        { "application/vnd.debian.binary-package", ".deb" },
        { "application/x-rpm", ".rpm" },
        { "application/x-iso9660-image", ".iso" },
        { "application/x-apple-diskimage", ".dmg" },

        // Data formats
        { "application/json", ".json" },
        { "application/xml", ".xml" },
        { "application/ld+json", ".jsonld" },
        { "application/java-archive", ".jar" },
        { "application/octet-stream", ".bin" },
        { "application/x-yaml", ".yaml" },
        { "application/x-www-form-urlencoded", ".url" },
        { "application/x-protobuf", ".proto" },
        { "application/msgpack", ".msgpack" },
        { "application/x-bson", ".bson" },
        { "application/x-sql", ".sql" },
        { "application/x-httpd-php", ".php" },
        { "application/javascript", ".js" },
        { "application/typescript", ".ts" },
        { "application/wasm", ".wasm" },
        { "application/graphql", ".graphql" },

        // Fonts
        { "font/ttf", ".ttf" },
        { "font/otf", ".otf" },
        { "font/woff", ".woff" },
        { "font/woff2", ".woff2" },
        { "font/collection", ".ttc" },
        { "application/vnd.ms-fontobject", ".eot" },

        // Other
        { "application/xhtml+xml", ".xhtml" },
        { "application/x-sh", ".sh" },
        { "application/x-csh", ".csh" },
        { "application/x-httpd-php", ".php" },
        { "application/x-freearc", ".arc" },
        { "application/vnd.visio", ".vsd" },
        { "application/x-abiword", ".abw" },
        { "application/vnd.android.package-archive", ".apk" },
        { "application/x-shockwave-flash", ".swf" },
        { "application/x-msdownload", ".exe" },
        { "application/x-ms-installer", ".msi" },
        { "application/x-bittorrent", ".torrent" },
        { "application/x-executable", ".elf" },
        { "application/x-dvi", ".dvi" },
        { "application/x-latex", ".latex" },
        { "application/x-texinfo", ".texi" },
        { "application/mxf", ".mxf" },
        { "application/sdp", ".sdp" },
        { "application/smil", ".smil" },
        { "application/x-mpegURL", ".m3u8" },
        { "application/dash+xml", ".mpd" },
        { "application/vnd.apple.installer+xml", ".mpkg" },
        { "application/vnd.microsoft.portable-executable", ".exe" }
    };
    return map.contains(mime) ? map.at(mime) : ".bin";
}


std::string get_mime(std::string extension) {
    const static std::unordered_map<std::string, std::string> map = {
        // Text
        { ".txt", "text/plain" },
        { ".html", "text/html" },
        { ".htm", "text/html" },
        { ".css", "text/css" },
        { ".js", "text/javascript" },
        { ".mjs", "text/javascript" },
        { ".md", "text/markdown" },
        { ".csv", "text/csv" },
        { ".c", "text/x-c" },
        { ".cpp", "text/x-c++" },
        { ".cc", "text/x-c++" },
        { ".cxx", "text/x-c++" },
        { ".h", "text/x-c" },
        { ".hpp", "text/x-c++" },
        { ".java", "text/x-java" },
        { ".py", "text/x-python" },
        { ".pyc", "application/x-python-code" },
        { ".pl", "text/x-perl" },
        { ".pm", "text/x-perl" },
        { ".rb", "text/x-ruby" },
        { ".go", "text/x-go" },
        { ".rs", "text/x-rust" },
        { ".swift", "text/x-swift" },
        { ".kt", "text/x-kotlin" },
        { ".scala", "text/x-scala" },
        { ".tex", "text/x-tex" },
        { ".yaml", "text/x-yaml" },
        { ".yml", "text/x-yaml" },
        { ".properties", "text/x-properties" },
        { ".ini", "text/plain" },
        { ".conf", "text/plain" },
        { ".cfg", "text/plain" },
        { ".log", "text/x-log" },
        { ".ics", "text/calendar" },
        { ".vcf", "text/vcard" },

        // Images
        { ".jpg", "image/jpeg" },
        { ".jpeg", "image/jpeg" },
        { ".jpe", "image/jpeg" },
        { ".png", "image/png" },
        { ".gif", "image/gif" },
        { ".webp", "image/webp" },
        { ".svg", "image/svg+xml" },
        { ".bmp", "image/bmp" },
        { ".tiff", "image/tiff" },
        { ".tif", "image/tiff" },
        { ".ico", "image/x-icon" },
        { ".cur", "image/x-icon" },
        { ".heic", "image/heic" },
        { ".heif", "image/heif" },
        { ".avif", "image/avif" },
        { ".apng", "image/apng" },

        // Audio
        { ".mp3", "audio/mpeg" },
        { ".ogg", "audio/ogg" },
        { ".oga", "audio/ogg" },
        { ".wav", "audio/wav" },
        { ".weba", "audio/webm" },
        { ".aac", "audio/aac" },
        { ".midi", "audio/midi" },
        { ".mid", "audio/x-midi" },
        { ".flac", "audio/flac" },
        { ".opus", "audio/opus" },
        { ".m4a", "audio/mp4" },
        { ".wma", "audio/x-ms-wma" },
        { ".aiff", "audio/x-aiff" },

        // Video
        { ".mp4", "video/mp4" },
        { ".m4v", "video/mp4" },
        { ".mpeg", "video/mpeg" },
        { ".mpg", "video/mpeg" },
        { ".mpe", "video/mpeg" },
        { ".webm", "video/webm" },
        { ".ogv", "video/ogg" },
        { ".avi", "video/x-msvideo" },
        { ".3gp", "video/3gpp" },
        { ".3g2", "video/3gpp2" },
        { ".ts", "video/mp2t" },
        { ".mkv", "video/x-matroska" },
        { ".mk3d", "video/x-matroska" },
        { ".wmv", "video/x-ms-wmv" },
        { ".flv", "video/x-flv" },
        { ".mov", "video/quicktime" },
        { ".qt", "video/quicktime" },
        { ".asf", "video/x-ms-asf" },

        // Documents
        { ".pdf", "application/pdf" },
        { ".doc", "application/msword" },
        { ".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
        { ".xls", "application/vnd.ms-excel" },
        { ".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
        { ".ppt", "application/vnd.ms-powerpoint" },
        { ".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
        { ".rtf", "application/rtf" },
        { ".odt", "application/vnd.oasis.opendocument.text" },
        { ".ods", "application/vnd.oasis.opendocument.spreadsheet" },
        { ".odp", "application/vnd.oasis.opendocument.presentation" },
        { ".odg", "application/vnd.oasis.opendocument.graphics" },
        { ".odc", "application/vnd.oasis.opendocument.chart" },
        { ".odf", "application/vnd.oasis.opendocument.formula" },
        { ".epub", "application/epub+zip" },
        { ".mobi", "application/x-mobipocket-ebook" },
        { ".azw", "application/vnd.amazon.ebook" },
        { ".dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template" },
        { ".xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template" },
        { ".potx", "application/vnd.openxmlformats-officedocument.presentationml.template" },

        // Archives
        { ".zip", "application/zip" },
        { ".7z", "application/x-7z-compressed" },
        { ".rar", "application/x-rar-compressed" },
        { ".gz", "application/gzip" },
        { ".tgz", "application/gzip" },
        { ".tar", "application/x-tar" },
        { ".bz", "application/x-bzip" },
        { ".bz2", "application/x-bzip2" },
        { ".xz", "application/x-xz" },
        { ".zst", "application/x-zstd" },
        { ".deb", "application/vnd.debian.binary-package" },
        { ".rpm", "application/x-rpm" },
        { ".iso", "application/x-iso9660-image" },
        { ".dmg", "application/x-apple-diskimage" },

        // Data formats
        { ".json", "application/json" },
        { ".xml", "application/xml" },
        { ".jsonld", "application/ld+json" },
        { ".jar", "application/java-archive" },
        { ".war", "application/java-archive" },
        { ".ear", "application/java-archive" },
        { ".bin", "application/octet-stream" },
        { ".dat", "application/octet-stream" },
        { ".yaml", "application/x-yaml" },
        { ".yml", "application/x-yaml" },
        { ".proto", "application/x-protobuf" },
        { ".msgpack", "application/msgpack" },
        { ".bson", "application/x-bson" },
        { ".sql", "application/x-sql" },
        { ".php", "application/x-httpd-php" },
        { ".phtml", "application/x-httpd-php" },
        { ".wasm", "application/wasm" },
        { ".graphql", "application/graphql" },

        // Fonts
        { ".ttf", "font/ttf" },
        { ".otf", "font/otf" },
        { ".woff", "font/woff" },
        { ".woff2", "font/woff2" },
        { ".ttc", "font/collection" },
        { ".eot", "application/vnd.ms-fontobject" },

        // Other
        { ".xhtml", "application/xhtml+xml" },
        { ".xht", "application/xhtml+xml" },
        { ".sh", "application/x-sh" },
        { ".csh", "application/x-csh" },
        { ".arc", "application/x-freearc" },
        { ".vsd", "application/vnd.visio" },
        { ".vsdx", "application/vnd.visio" },
        { ".abw", "application/x-abiword" },
        { ".apk", "application/vnd.android.package-archive" },
        { ".swf", "application/x-shockwave-flash" },
        { ".exe", "application/x-msdownload" },
        { ".msi", "application/x-ms-installer" },
        { ".torrent", "application/x-bittorrent" },
        { ".elf", "application/x-executable" },
        { ".dvi", "application/x-dvi" },
        { ".latex", "application/x-latex" },
        { ".texi", "application/x-texinfo" },
        { ".texinfo", "application/x-texinfo" },
        { ".mxf", "application/mxf" },
        { ".sdp", "application/sdp" },
        { ".smil", "application/smil" },
        { ".m3u8", "application/x-mpegURL" },
        { ".mpd", "application/dash+xml" },
        { ".mpkg", "application/vnd.apple.installer+xml" }
    };
    return map.contains(extension) ? map.at(extension) : "application/octet-stream";
}